# Generated by Django 5.0.6 on 2024-05-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lie',
            field=models.BooleanField(default=True, verbose_name='правда'),
        ),
    ]
